apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment.yaml
  - service.yaml
images:
  - name: IMAGE_NAME
    newName: ${{ secrets.DOCKER_USERNAME }}/${{ github.event.repository.name }}
    newTag: latest