name: CI Pipeline for Sentiment API

on:
    push:
        branches:
            - main


jobs:
    test:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v5

            - name: Install project dependencies
              uses: pip install -r requirements.txt

            - name: Run Pytest
              uses: pytest
    
    build-and-push:
        needs: test # only run this once test job is successful
        runs-on: ubuntu-latest
        env:
            IMAGE_NAME: ${{ secrets.DOCKER_USERNAME }}/${{ github.event.repository.name }}

        steps:
            - name: Checkout repository
              uses: actions/checkout@v5

            - name: Login to Docker hub
              uses: docker/login-action@v3
              with:
                username: ${{ secrets.DOCKERHUB_USERNAME }}
                password: ${{ secrets.DOCKERHUB_TOKEN }}

            - name: Build and push Docker image
              uses: docker/build-push-action@v5
              with:
                context: .
                file: ./Dockerfile
                push: true
                tags: |
                    ${{ env.IMAGE_NAME }}:latest
                    ${{ env.IMAGE_NAME }}:${{ github.sha }}


