name: CI Pipeline for Sentiment API

on:
    push:
        branches:
            - main


jobs:
    test:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v5
            
            - name: Set up Python
              uses: actions/setup-python@v4
              with:
                python-version: '3.10'

            - name: Install project dependencies
              run: pip install -r requirements.txt # run for shell commands

            - name: Run Pytest
              run: pytest
    
    build-and-push:
        needs: test # only run this once test job is successful
        runs-on: ubuntu-latest
        env:
            IMAGE_NAME: ${{ secrets.DOCKERHUB_USERNAME }}/${{ github.event.repository.name }}

        steps:
            - name: Checkout repository
              uses: actions/checkout@v5

            - name: Login to Docker hub
              uses: docker/login-action@v3
              with:
                username: ${{ secrets.DOCKERHUB_USERNAME }}
                password: ${{ secrets.DOCKERHUB_TOKEN }}

            - name: Build and push Docker image
              uses: docker/build-push-action@v5
              with:
                context: .
                file: ./Dockerfile
                push: true
                tags: |
                    ${{ env.IMAGE_NAME }}:latest
                    ${{ env.IMAGE_NAME }}:${{ github.sha }}
    deploy:
        needs: build-and-push
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v5

            - name: Install kustomize
              run: |
                curl -s "https://raw.githubusercontent.com/kubernetes-sigs/kustomize/master/hack/install_kustomize.sh" | bash
                sudo mv kustomize /usr/local/bin/

            - name: Update image tag with kustomize
              run: |
                cd k8s
                kustomize edit set image IMAGE_NAME=${{ secrets.DOCKERHUB_USERNAME }}/${{ github.event.repository.name }}:${{ github.sha }}

            - name: Configure git
              run: |
                git config --global user.name "github-actions[bot]"
                git config --global user.email "github-actions[bot]@users.noreply.github.com"

            - name: Commit and push changes
              run: |
                git add k8s/kustomization.yaml
                git commit -m "[CI SKIP] Update image tag to ${{ github.sha }}"
                git push



