name: CI/CD Pipeline for Sentiment API

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: write  # Add this to allow pushing commits


jobs:
    test:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v5
            
            - name: Set up Python
              uses: actions/setup-python@v4
              with:
                python-version: '3.10'

            - name: Install project dependencies
              run: pip install -r requirements.txt # run for shell commands

            - name: Run Pytest
              run: pytest

    build-and-push:
        needs: test # only run this once test job is successful
        runs-on: ubuntu-latest
        env:
            IMAGE_NAME: ${{ secrets.DOCKERHUB_USERNAME }}/${{ github.event.repository.name }}

        steps:
            - name: Checkout repository
              uses: actions/checkout@v5

            - name: Login to Docker hub
              uses: docker/login-action@v3
              with:
                username: ${{ secrets.DOCKERHUB_USERNAME }}
                password: ${{ secrets.DOCKERHUB_TOKEN }}

            - name: Build and Push Docker image
              uses: docker/build-push-action@v5
              with:
                context: .
                file: ./Dockerfile
                push: true
                tags: |
                    ${{ env.IMAGE_NAME }}:latest
                    ${{ env.IMAGE_NAME }}:${{ github.sha }}

    deploy:
        needs: build-and-push
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v5

            - name: Set new image tag
              # This command finds the line with "image:" in the deployment.yaml
              # and replaces the whole line with the new image tag.
              run: |
                sed -i "s|image: .*|image: ${{ secrets.DOCKERHUB_USERNAME }}/${{ github.event.repository.name }}:${{ github.sha }}|g" k8s/deployment.yaml

            - name: Configure git
              run: |
                git config --global user.name "GitHub Actions Bot"
                git config --global user.email "actions-bot@github.com"

            - name: Commit and Push changes
              run: |
                git add k8s/deployment.yaml
                # Check if there are changes to commit
                if ! git diff --staged --quiet; then
                    git commit -m "[CI SKIP] Update deployment image to ${{ github.sha }}"
                    git push
                else
                    echo "No changes to commit."
                fi




